[package]

name = "duktape"
version = "0.0.1"
authors = ["Eric Kidd <git@randomhacks.net>"]

description = "Embedded JavaScript interpreter with a small footprint"
license = "MIT"

repository = "https://github.com/emk/duktape-rs"

[dependencies.duktape_sys]
path = "duktape_sys"
version = "*"
